name = "MyExample"
uuid = "97480628-8167-447e-ac79-cae0109701ec"
authors = ["Kartikey Mullick"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
